version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "3030:3030"
    container_name: music_meta_web
    environment:
      POSTGRES_DB: "music_meta_docker_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: db
    depends_on:
      - db
    restart: always
    networks:
      - music_meta_web_net
    volumes:
      - .:/music_meta_web
    command: >
      sh -c "python manage.py runserver 0.0.0.0:3030"

  db:
    image: postgres
    environment:
      POSTGRES_DB: "music_meta_docker_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
    - "5433:5432"
    restart: on-failure
    volumes:
    - music_meta_web_db_data:/var/lib/postgresql/data3
    networks:
      - music_meta_web_net

networks:
  music_meta_web_net:
    driver: bridge

volumes:
  music_meta_web_db_data: