# Generated by Django 4.0.4 on 2022-05-08 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8bebfdac-e03f-46c3-806c-b530af3b1ab0'), primary_key=True, serialize=False),
        ),
    ]
